spring.application.name=DevMind

#datasource
spring.datasource.url=jdbc:mariadb://localhost:3306/devmind
spring.datasource.username=dev
spring.datasource.password=dev1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#jpa
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
